export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  MFA_REQUIRED: 'MFA_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  MAPS_API_ERROR: 'MAPS_API_ERROR',
  SMS_GATEWAY_ERROR: 'SMS_GATEWAY_ERROR',
  VIDEO_PROCESSING_ERROR: 'VIDEO_PROCESSING_ERROR',
  MODERATION_API_ERROR: 'MODERATION_API_ERROR',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ESCROW_FROZEN: 'ESCROW_FROZEN',
  KYC_NOT_APPROVED: 'KYC_NOT_APPROVED',
  STORE_SUSPENDED: 'STORE_SUSPENDED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
