import { Product, ProductCategory, QualityTier } from '@wunabuy/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    store_id: 'store_101',
    name: 'Samsung Galaxy A54 5G (128GB, 8GB RAM)',
    description: 'Brand new, sealed in box with 1-year official Samsung warranty. 50MP OIS camera, 5000mAh battery, Super AMOLED display.',
    category: ProductCategory.ELECTRONICS,
    price: 185000,
    currency: 'XAF',
    quantity: 8,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_reviews: 34,
    distance_km: 1.8,
    store: {
      id: 'store_101',
      store_name: 'Douala Tech Hub (Akwa)',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    store_id: 'store_102',
    name: 'MacBook Air M2 13.6" (256GB SSD, Midnight)',
    description: 'Like new condition, pristine keyboard, 99% battery health. Comes with original MagSafe charger and leather sleeve.',
    category: ProductCategory.ELECTRONICS,
    price: 650000,
    currency: 'XAF',
    quantity: 2,
    quality_tier: QualityTier.LIKE_NEW,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_reviews: 19,
    distance_km: 3.2,
    store: {
      id: 'store_102',
      store_name: 'Bonanjo iStore',
      rating_avg: 4.8,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    store_id: 'store_103',
    name: 'Traditional Bamenda Toghu Embroidered Outfit',
    description: 'Authentic hand-embroidered Toghu ceremonial tunic and trousers. High quality velvet fabric, tailored in Bamenda.',
    category: ProductCategory.FASHION,
    price: 45000,
    currency: 'XAF',
    quantity: 5,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 5.0,
    total_reviews: 42,
    distance_km: 2.5,
    store: {
      id: 'store_103',
      store_name: 'Heritage African Couture',
      rating_avg: 5.0,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    store_id: 'store_104',
    name: 'Fresh Cameroon Penja White Pepper (500g Bag)',
    description: 'World-famous PGI-certified Penja White Pepper. Direct from Penja plantations, perfect for gourmet dishes.',
    category: ProductCategory.FOOD_GROCERIES,
    price: 12500,
    currency: 'XAF',
    quantity: 50,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_reviews: 88,
    distance_km: 0.9,
    store: {
      id: 'store_104',
      store_name: 'Penja Organic Farm Shop',
      rating_avg: 4.7,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_5',
    store_id: 'store_101',
    name: 'Sony WH-1000XM5 ANC Headphones (Black)',
    description: 'Industry-leading noise cancellation, 30h battery life, touch control, pristine condition.',
    category: ProductCategory.ELECTRONICS,
    price: 210000,
    currency: 'XAF',
    quantity: 3,
    quality_tier: QualityTier.GOOD,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.6,
    total_reviews: 14,
    distance_km: 1.8,
    store: {
      id: 'store_101',
      store_name: 'Douala Tech Hub (Akwa)',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    store_id: 'store_105',
    name: 'Nike Air Force 1 "07 Low (White, Size 43)',
    description: 'Classic crisp white leather sneakers. Unboxed but unused.',
    category: ProductCategory.FASHION,
    price: 35000,
    currency: 'XAF',
    quantity: 1,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.5,
    total_reviews: 26,
    distance_km: 4.1,
    store: {
      id: 'store_105',
      store_name: 'Urban Kicks Douala',
      rating_avg: 4.6,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

