import { Product, ProductCategory, QualityTier } from '@wunabuy/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    store_id: 'store_101',
    name: 'Glow Radiance Serum',
    description: 'Brightening & Glow daily serum. Hydrates deeply and protects skin barrier with 10% Niacinamide & Vitamin C.',
    category: ProductCategory.HEALTH_BEAUTY,
    price: 18500,
    currency: 'XAF',
    quantity: 15,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1608248597262-838d89066dfd?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_reviews: 126,
    distance_km: 1.2,
    store: {
      id: 'store_101',
      store_name: 'Luxe Beauty Douala',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    store_id: 'store_101',
    name: 'Hydra Moisturizer Cream',
    description: '24H intense hydration cream with hyaluronic acid and shea butter for radiant, smooth skin.',
    category: ProductCategory.HEALTH_BEAUTY,
    price: 14500,
    currency: 'XAF',
    quantity: 20,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_reviews: 98,
    distance_km: 1.2,
    store: {
      id: 'store_101',
      store_name: 'Luxe Beauty Douala',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    store_id: 'store_101',
    name: 'Velvet Matte Lipstick',
    description: 'Long-lasting rich pigment color with non-drying matte finish. Transfer-proof 16h wear.',
    category: ProductCategory.HEALTH_BEAUTY,
    price: 9500,
    currency: 'XAF',
    quantity: 30,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_reviews: 156,
    distance_km: 1.2,
    store: {
      id: 'store_101',
      store_name: 'Luxe Beauty Douala',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    store_id: 'store_101',
    name: 'Glow Silk Foundation',
    description: 'Natural finish light-reflecting liquid foundation. Seamless coverage for all skin tones.',
    category: ProductCategory.HEALTH_BEAUTY,
    price: 16500,
    currency: 'XAF',
    quantity: 12,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1599733589046-9b8308b5b50d?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_reviews: 112,
    distance_km: 1.2,
    store: {
      id: 'store_101',
      store_name: 'Luxe Beauty Douala',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_5',
    store_id: 'store_102',
    name: 'Samsung Galaxy A54 5G (128GB)',
    description: 'Brand new sealed in box with 1-year official Samsung warranty. 50MP OIS camera, Super AMOLED display.',
    category: ProductCategory.ELECTRONICS,
    price: 185000,
    currency: 'XAF',
    quantity: 8,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_reviews: 34,
    distance_km: 1.8,
    store: {
      id: 'store_102',
      store_name: 'Douala Tech Hub (Akwa)',
      rating_avg: 4.9,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    store_id: 'store_103',
    name: 'Traditional Bamenda Toghu Outfit',
    description: 'Authentic hand-embroidered Toghu ceremonial tunic and trousers. High quality velvet fabric.',
    category: ProductCategory.FASHION,
    price: 45000,
    currency: 'XAF',
    quantity: 5,
    quality_tier: QualityTier.NEW,
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    ],
    is_active: true,
    rating_avg: 5.0,
    total_reviews: 42,
    distance_km: 2.5,
    store: {
      id: 'store_103',
      store_name: 'Heritage African Couture',
      rating_avg: 5.0,
      is_verified: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
